/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_stu_cusview_ruiz_customeviewdemo_jnitest_JniUtil */

#ifndef _Included_cn_stu_cusview_ruiz_customeviewdemo_jnitest_JniUtil
#define _Included_cn_stu_cusview_ruiz_customeviewdemo_jnitest_JniUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_stu_cusview_ruiz_customeviewdemo_jnitest_JniUtil
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cn_stu_cusview_ruiz_customeviewdemo_jnitest_JniUtil_getString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
